server:
  port: 8081
spring:
  application:
    name: hexagonal
  data:
    mongodb:
      hast: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal
birapcampos:
  client:
    address:
      url: http://localhost:8082/addresses
